In [5]:
# import packages

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [6]:
# import data
spam_df = pd.read_csv("spam.csv")

In [13]:
# inspect data
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [14]:
# vectorizing the data, creating new column for spam/ham
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
spam_df

In [22]:
# create train/test split
X_train, x_test, Y_train, y_test = train_test_split(spam_df.Message, spam_df.spam, test_size=0.2)

In [32]:
# find word count and store data as a matrix
cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
# train model
model = MultinomialNB()
model.fit(X_train_count, Y_train)

MultinomialNB()

In [44]:
# pre-test ham email

email_ham = ['baseball tickets later lets meet up']
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0])

In [43]:
# pre-test spam email
email_spam = ['reward money click here to claim your prize!']
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

In [45]:
# test model
X_test_count = cv.transform(x_test)
model.score(X_test_count, y_test)

0.9856502242152466